version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: proyecto-microservicios-postgres-1
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: usersdb
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8.4
    container_name: proyecto-microservicios-mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productsdb
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306"   # host:container
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:6
    container_name: proyecto-microservicios-mongo-1
    command: ["--replSet","rs0","--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  pg_data:
  mysql_data:
  mongo_data:
