export const toPublicUser = (user: any) => ({
    id: user.id,
    email: user.email,
    roles: user.roles ? user.roles.split(',') : [],
    isActive: user.isActive,
    firstName: user.firstName,
    lastName: user.lastName,
    phone: user.phone,
    addressLine: user.addressLine,
    city: user.city,
    state: user.state,
    postalCode: user.postalCode,
    country: user.country,
    avatarUrl: user.avatarUrl,
    birthDate: user.birthDate,
    createdAt: user.createdAt,
    updatedAt: user.updatedAt,
});
